CREATE TABLE EMPLOYEE (
    ID VARCHAR(255)  NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    EmployeeEMailAddress NVARCHAR(255) NOT NULL,
    EmployeeSiteID NVARCHAR(255) NOT NULL,
    EmployeeLocalID NVARCHAR(255) NOT NULL,
    faceTemplate NVARCHAR(MAX) NULL,
    keyPhoto NVARCHAR(MAX) NULL,

    CONSTRAINT PK_EMPLOYEE PRIMARY KEY CLUSTERED (id),
    CONSTRAINT UQ_EMPLOYEE_email UNIQUE (EmployeeEMailAddress)
)

INSERT INTO EMPLOYEE (ID, Name, EmployeeEMailAddress, EmployeeSiteID, EmployeeLocalID, faceTemplate, keyPhoto)
VALUES
    ('E001', 'Ana Silva', 'ana.silva@empresa.com', 'SITE01', 'LOC101', NULL, NULL),
    ('E002', 'Bruno Souza', 'bruno.souza@empresa.com', 'SITE01', 'LOC102', NULL, NULL),
    ('E003', 'Carla Mendes', 'carla.mendes@empresa.com', 'SITE02', 'LOC103', NULL, NULL),
    ('E004', 'Daniel Costa', 'daniel.costa@empresa.com', 'SITE01', 'LOC104', NULL, NULL),
    ('E005', 'Elena Santos', 'elena.santos@empresa.com', 'SITE02', 'LOC105', NULL, NULL),
    ('E006', 'Fabio Junior', 'fabio.junior@empresa.com', 'SITE01', 'LOC106', NULL, NULL),
    ('E007', 'Gisele Costa', 'gisele.costa@empresa.com', 'SITE03', 'LOC107', NULL, NULL),
    ('E008', 'Helio Rocha', 'helio.rocha@empresa.com', 'SITE02', 'LOC108', NULL, NULL),
    ('E009', 'Igor Lima', 'igor.lima@empresa.com', 'SITE01', 'LOC109', NULL, NULL),
    ('E010', 'Julia Ferraz', 'julia.ferraz@empresa.com', 'SITE03', 'LOC110', NULL, NULL),
    ('E011', 'Kevin Castro', 'kevin.castro@empresa.com', 'SITE01', 'LOC111', NULL, NULL),
    ('E012', 'Larissa Melo', 'larissa.melo@empresa.com', 'SITE02', 'LOC112', NULL, NULL),
    ('E013', 'Mauricio Vaz', 'mauricio.vaz@empresa.com', 'SITE01', 'LOC113', NULL, NULL),
    ('E014', 'Nara Neves', 'nara.neves@empresa.com', 'SITE03', 'LOC114', NULL, NULL),
    ('E015', 'Otavio Pires', 'otavio.pires@empresa.com', 'SITE02', 'LOC115', NULL, NULL),
    ('E016', 'Paula Ramos', 'paula.ramos@empresa.com', 'SITE01', 'LOC116', NULL, NULL),
    ('E017', 'Quezia Dias', 'quezia.dias@empresa.com', 'SITE03', 'LOC117', NULL, NULL),
    ('E018', 'Ricardo Alves', 'ricardo.alves@empresa.com', 'SITE02', 'LOC118', NULL, NULL),
    ('E019', 'Sabrina Luz', 'sabrina.luz@empresa.com', 'SITE01', 'LOC119', NULL, NULL),
    ('E020', 'Tiago Monte', 'tiago.monte@empresa.com', 'SITE03', 'LOC120', NULL, NULL),
    ('E021', 'Ursula Meira', 'ursula.meira@empresa.com', 'SITE02', 'LOC121', NULL, NULL),
    ('E022', 'Vitor Hugo', 'vitor.hugo@empresa.com', 'SITE01', 'LOC122', NULL, NULL),
    ('E023', 'Wagner Moura', 'wagner.moura@empresa.com', 'SITE03', 'LOC123', NULL, NULL),
    ('E024', 'Xenia Soares', 'xenia.soares@empresa.com', 'SITE02', 'LOC124', NULL, NULL),
    ('E025', 'Yago Martins', 'yago.martins@empresa.com', 'SITE01', 'LOC125', NULL, NULL),
    ('E026', 'Zilda Cardoso', 'zilda.cardoso@empresa.com', 'SITE03', 'LOC126', NULL, NULL),
    ('E027', 'Andre Gomes', 'andre.gomes@empresa.com', 'SITE02', 'LOC127', NULL, NULL),
    ('E028', 'Beatriz Farias', 'beatriz.farias@empresa.com', 'SITE01', 'LOC128', NULL, NULL),
    ('E029', 'Caio Ribeiro', 'caio.ribeiro@empresa.com', 'SITE03', 'LOC129', NULL, NULL),
    ('E030', 'Dandara Paz', 'dandara.paz@empresa.com', 'SITE02', 'LOC130', NULL, NULL),
    ('E031', 'Erick Silva', 'erick.silva@empresa.com', 'SITE01', 'LOC131', NULL, NULL),
    ('E032', 'Fernanda Lima', 'fernanda.lima@empresa.com', 'SITE03', 'LOC132', NULL, NULL),
    ('E033', 'Gabriel Ohara', 'gabriel.ohara@empresa.com', 'SITE02', 'LOC133', NULL, NULL),
    ('E034', 'Hilda Prado', 'hilda.prado@empresa.com', 'SITE01', 'LOC134', NULL, NULL),
    ('E035', 'Iara Silveira', 'iara.silveira@empresa.com', 'SITE03', 'LOC135', NULL, NULL),
    ('E036', 'Jonas Brother', 'jonas.brother@empresa.com', 'SITE02', 'LOC136', NULL, NULL),
    ('E037', 'Kelly Key', 'kelly.key@empresa.com', 'SITE01', 'LOC137', NULL, NULL),
    ('E038', 'Luan Santana', 'luan.santana@empresa.com', 'SITE03', 'LOC138', NULL, NULL),
    ('E039', 'Mara Maravilha', 'mara.maravilha@empresa.com', 'SITE02', 'LOC139', NULL, NULL),
    ('E040', 'Neymar Junior', 'ney.jr@empresa.com', 'SITE01', 'LOC140', NULL, NULL);

